services:
  neo4j:
    image: neo4j:5.21
    restart: unless-stopped
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_server_default_listen__address: "0.0.0.0"
      NEO4J_server_default_advertised__address: "neo4j"
      NEO4J_server_bolt_listen__address: ":7687"
      NEO4J_server_bolt_advertised__address: "neo4j:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7474/ready || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 60s

  graphiti-app:
    image: python:3.11-slim
    restart: unless-stopped
    working_dir: /app
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      TZ: Europe/Amsterdam
    volumes:
      - .:/app
    # Вариант с requirements.txt
    command: >
      bash -lc "
      pip install --no-cache-dir -r requirements.txt
      && uvicorn app:app --host 0.0.0.0 --port 8000
      "
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  neo4j_data: {}
