services:
  graphiti-app:
    image: python:3.11
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=password
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install 'graphiti-core[google-genai]' && python your_entrypoint.py"
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:5.15
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7687:7687"
      - "7474:7474"
